;;==============================Hooks==============================
(add-to-list 'auto-mode-alist '(".zshrc$" . shell-script-mode))

(defun yasnippet-hook ()
  (autoload 'yas/global-mode "yasnippet" nil t)
  (yas/initialize)
  (global-set-key [backtab] `yas/expand)
  ;; (setq yas/snippet-dirs '("~/.emacs.d/snippets" "~/.emacs.d/el-get/yasnippet/extras/imported"))
  ;; (setq yas/root-directory "~/.emacs.d/snippets")
  ;; (yas/load-directory yas/root-directory)
  (yas/global-mode 1))

(defun ruby-mode-hook ()
  (autoload 'ruby-mode "ruby-mode" nil t)
  (add-to-list 'auto-mode-alist '("Capfile" . ruby-mode))
  (add-to-list 'auto-mode-alist '("Gemfile" . ruby-mode))
  (add-to-list 'auto-mode-alist '("Guardfile" . ruby-mode))
  (add-to-list 'auto-mode-alist '("Rakefile" . ruby-mode))  
  (add-to-list 'auto-mode-alist '("\\.rake\\'" . ruby-mode))
  (add-to-list 'auto-mode-alist '("\\.rb\\'" . ruby-mode))
  (add-to-list 'auto-mode-alist '("\\.ru\\'" . ruby-mode))
  (add-hook 'ruby-mode-hook
            '(lambda ()
               (setq ruby-deep-arglist t)
               (setq ruby-deep-indent-paren nil)
               (setq c-tab-always-indent nil)
               ;;(setq ruby-insert-encoding-magic-comment nil)
               ;;(remove-hook 'before-save-hook 'ruby-mode-set-encoding)
               ;;(defun ruby-mode-set-encoding () ())
               (require 'inf-ruby)
               (require 'ruby-compilation))))

(defun rhtml-mode-hook ()
  (autoload 'rhtml-mode "rhtml-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.erb\\'" . rhtml-mode))
  (add-to-list 'auto-mode-alist '("\\.rjs\\'" . rhtml-mode)))

(defun yaml-mode-hook ()
  (autoload 'yaml-mode "yaml-mode" nil t)
  (add-to-list 'auto-mode-alist '("\\.yml$" . yaml-mode))
  (add-to-list 'auto-mode-alist '("\\.yaml$" . yaml-mode)))

(defun css-mode-hook ()
  (autoload 'css-mode "css-mode" nil t)
  (add-hook 'css-mode-hook '(lambda ()
                              (setq css-indent-level 2)
                              (setq css-indent-offset 2))))

(defun feature-mode-hook ()
  (autoload 'feature-mode "feature-mode" nil t)
  (add-to-list 'auto-mode-alist '("\.feature$" . feature-mode)))

(defun sass-mode-hook ()
  (autoload 'sass-mode "sass-mode" nil t)
  (add-to-list 'auto-mode-alist '("\.scss$" . sass-mode))
  (add-to-list 'auto-mode-alist '("\.sass$" . sass-mode)))

(defun markdown-mode-hook ()
  (autoload 'markdown-mode "markdown-mode.el"
    "Major mode for editing Markdown files" t)
  (add-to-list 'auto-mode-alist '("\\.markdown" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.text" . markdown-mode)))
